### ISSUE TITLE
Issues installing under Windows, which versions of libraries, dependencies to use?

### ISSUE THREAD

**Issue by schorhr** [mark-orion/PyFSPro#2]
Hello :-)

I am using Windows 10, 64 bit, and struggle getting it to work. I have very, very little experience with Python.

I am following Following INSTALL_WIN.md.

To avoid downward compatibility issues I tried with Python 2.7 by downloading Anaconda2-2.5.0-Windows-x86_64.
And opencv-2.4.13.

python -m pip install --upgrade pip wheel setuptools fails and thus running _python PyFSPro.py_:

> [CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
> sdl2 - ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
>   File "C:\Anaconda2\lib\site-packages\kivy\core\__init__.py", line 63, in core_select_lib
>     fromlist=[modulename], level=0)
>   File "C:\Anaconda2\lib\site-packages\kivy\core\window\window_sdl2.py", line 27, in <module>
>     from kivy.core.window._window_sdl2 import _WindowSDL2Storage
> 
>  Traceback (most recent call last):
>    File "PyFSPro.py", line 47, in <module>
>      import actuators as acts
>    File "C:\PyFSPro-master\actuators.py", line 18, in <module>
>      import liblo
>  ImportError: No module named liblo

Installing liblo (pyliblo) manually didn't work, downloading VCForPython27 I still get this error:

> C:\Users\Me\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda2\include -IC:\Anaconda2\PC /Tcsrc/liblo.c /Fobuild\temp.win-amd64-2.7\Release\src/liblo.obj -fno-strict-aliasing -Werror-implicit-function-declaration -Wfatal-errors
cl : Command line error D8021 : invalid numeric argument '/Werror-implicit-function-declaration'
error: command 'C:\\Users\\Me\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

Could anyone point me to the right versions I need to use, or how to resolve the error(s)?

I apologize if this is a bit unorganized, I tried different ways to install dependencies and fix the errors (and if I worded something wrong, English isn't my native language).

I am trying to get this to work during a project after regular school classes to observe air flow, thermal currents with students, and the effect of wearing different types of masks.

Thank you ._)

**Comment by Ronald77777** [comment]
I have problems with liblo, I tried to download it, I already downloaded liblo but I can't download the python module if you can help me please

**Comment by schorhr** [comment]
Any luck, ideas, help, fixes?
